#!/usr/bin/env bash
# scripts/resolve-vars.sh
#
# Queries the Supervisor cluster via kubectl to discover Kubernetes resource
# names and writes them to a Packer variables file.
#
# Invoked by Packer as a shell-local provisioner (see resolve.pkr.hcl).
# All inputs come from environment variables set by Packer.
#
# Required env vars:
#   NAMESPACE             Supervisor namespace
#   OUTPUT_FILE           Path to write the resolved variables file
#
# Optional env vars (resolved when non-empty):
#   IMPORT_IMAGE_NAME     Friendly name of the uploaded ISO → resolves image_name
#   STAGE1_PUBLISH_NAME   Name of Stage 1 published image → resolves stage2_image_name
#   PUBLISH_LIBRARY_NAME  Human-readable library name → resolves stage1_publish_location_name and stage2_publish_location_name
#
# Required tools: kubectl, jq

set -euo pipefail

NAMESPACE="${NAMESPACE:?NAMESPACE is required}"
OUTPUT_FILE="${OUTPUT_FILE:?OUTPUT_FILE is required}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

check_deps() {
  local missing=()
  for cmd in kubectl jq; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done
  if (( ${#missing[@]} )); then
    die "Missing required tools: ${missing[*]}"
  fi
}

# ── kubectl helpers ──────────────────────────────────────────────────────────

lookup_vmi() {
  local friendly_name="$1"
  kubectl get virtualmachineimage -n "$NAMESPACE" -o json 2>/dev/null | \
    jq -r --arg name "$friendly_name" '
      [.items[] | select(
        .status.imageName == $name or
        .status.name == $name or
        .spec.imageName == $name or
        (.metadata.name | test($name; "i"))
      )] | first | .metadata.name // empty'
}

lookup_library() {
  local friendly_name="$1" libraries="$2"
  echo "$libraries" | jq -r --arg name "$friendly_name" '
    [.items[] | select(
      .status.name == $name or
      .spec.name == $name or
      (.metadata.name | test($name; "i"))
    )] | first | .metadata.name // empty'
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
  check_deps
  mkdir -p "$(dirname "$OUTPUT_FILE")"

  declare -a LINES=()
  LINES+=("// Auto-generated by: packer build -only=\"resolve-vars.null.resolve\"")
  LINES+=("// Re-run \`make resolve\` to refresh. Delete this file to use manual values.")
  LINES+=("")

  local found=0

  # ── VirtualMachineImage resolution ────────────────────────────────────

  if [ -n "${IMPORT_IMAGE_NAME:-}" ]; then
    log "Resolving image_name from \"${IMPORT_IMAGE_NAME}\" ..."
    local vmi
    vmi="$(lookup_vmi "$IMPORT_IMAGE_NAME")"
    if [ -n "$vmi" ]; then
      log "  image_name = \"${vmi}\""
      LINES+=("image_name = \"${vmi}\"")
      found=1
    else
      warn "No VirtualMachineImage matching \"${IMPORT_IMAGE_NAME}\""
    fi
  fi

  if [ -n "${STAGE1_PUBLISH_NAME:-}" ]; then
    log "Resolving stage2_image_name from \"${STAGE1_PUBLISH_NAME}\" ..."
    local vmi
    vmi="$(lookup_vmi "$STAGE1_PUBLISH_NAME")"
    if [ -n "$vmi" ]; then
      log "  stage2_image_name = \"${vmi}\""
      LINES+=("stage2_image_name = \"${vmi}\"")
      found=1
    else
      warn "No VirtualMachineImage matching \"${STAGE1_PUBLISH_NAME}\""
    fi
  fi

  # ── ContentLibrary resolution ─────────────────────────────────────────

  local libraries
  libraries=$(kubectl get contentlibrary -n "$NAMESPACE" -o json 2>/dev/null || echo '{"items":[]}')

  if [ -n "${PUBLISH_LIBRARY_NAME:-}" ]; then
    log "Resolving publish_location_name from \"${PUBLISH_LIBRARY_NAME}\" ..."
    local crd
    crd="$(lookup_library "$PUBLISH_LIBRARY_NAME" "$libraries")"
    if [ -n "$crd" ]; then
      log "  stage1_publish_location_name = \"${crd}\""
      log "  stage2_publish_location_name = \"${crd}\""
      LINES+=("stage1_publish_location_name = \"${crd}\"")
      LINES+=("stage2_publish_location_name = \"${crd}\"")
      found=1
    else
      warn "No ContentLibrary matching \"${PUBLISH_LIBRARY_NAME}\""
    fi
  fi

  # ── Write output ──────────────────────────────────────────────────────

  if [ "$found" -eq 1 ]; then
    printf '%s\n' "${LINES[@]}" > "$OUTPUT_FILE"
    log "Wrote ${OUTPUT_FILE}"
  else
    warn "Nothing resolved — ${OUTPUT_FILE} not written"
  fi

  # ── Reference listing ─────────────────────────────────────────────────

  log "Available VirtualMachineImage resources:"
  kubectl get virtualmachineimage -n "$NAMESPACE" --no-headers 2>/dev/null | \
    awk '{print "  " $1}' || echo "  (none)"
  log "Available ContentLibrary resources:"
  echo "$libraries" | jq -r '.items[] | "  \(.metadata.name)\t\(.status.name // .spec.name // "—")"' 2>/dev/null || \
    echo "  (none)"
}

main "$@"
